services:
  y2o:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: y2o
    # volumes:
      # - ./data:/app/data
      # - ./logs:/app/logs
      # - ./certs:/app/certs
    ports:
      - "8520:8520"
    env_file:
      - stack.env
    restart: unless-stopped